### ISSUE TITLE
Issue with CORS in 4.2.0?

### ISSUE THREAD

**Issue by tyrex1975** [igniterealtime/openfire-jsxc-plugin#5]
Hi there, I'm using this JSXC plugin on my Openfire server.

Prior to this 4.2.0 release (4.1.1) everything worked fine, since updating, I am receiving CORS issues with the font files being delivered by the plugin. All of the other downloads e.g. JS/CSS/graphics files come down fine.

![image](https://user-images.githubusercontent.com/7656443/102553760-4d027200-40bb-11eb-8eb7-3580ecd4c306.png)

![image](https://user-images.githubusercontent.com/7656443/102553577-f8f78d80-40ba-11eb-9dd5-bf9f243debf8.png)

Have I messed something up?

**Comment by Fishbowler** [comment]
I can't reproduce this on port 7070 or 7443. Are you still having the problem?

**Comment by guusdk** [comment]
This issue seems stale. I'm closing it for now. Feel free to revive this if the problem re-appears.
